### ISSUE TITLE
tex to ipynb script

### ISSUE THREAD

**Issue by vincentdavis** [tiagoantao/biopython-notebook#3]
In the branch;
https://github.com/tiagoantao/biopython-notebook/tree/tex-ipynb-convert 
I have added a scripts folded and a script to convert the tutorial tex files to ipynb. It mostly works ok.
You can see the converted notebooks here;
https://github.com/vincentdavis/biopython-notebook/tree/tex-ipynb-convert/Tutorial
I figured this folder might also be useful for a scripts to download data files.

Is this script something you want to include?

**Comment by tiagoantao** [comment]
This is great!

What about, instead of including the script, we just put the converted
notebooks there? I suspect that after the first conversion i will make
sense to start diverging from the core tutorial. The notebook format is not
a perfect mapping for the tutorial content...

On 13 December 2015 at 19:48, Vincent <notifications@github.com> wrote:

> In the branch;
> https://github.com/tiagoantao/biopython-notebook/tree/tex-ipynb-convert
> I have added a scripts folded and a script to convert the tutorial tex
> files to ipynb. It mostly works ok.
> You can see the converted notebooks here;
>
> https://github.com/vincentdavis/biopython-notebook/tree/tex-ipynb-convert/Tutorial
> I figured this folder might also be useful for a scripts to download data
> files.
>
> Is this script something you want to include?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tiagoantao/biopython-notebook/issues/3>.
>



-- 
"Democracy matters more than any currency arrangement." - Paul Krugman

**Comment by vincentdavis** [comment]
I pushed the converted notebooks to master, I hope that is what you wanted.
